# Generated by Django 4.0.6 on 2022-07-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=60)),
                ('price', models.IntegerField(db_column='price', max_length=5)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.categorys')),
            ],
        ),
    ]
