# Generated by Django 4.0.6 on 2022-07-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_id',
            new_name='c_id',
        ),
    ]
