# Generated by Django 4.0.6 on 2022-07-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_p_id_products_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='c_id',
            new_name='category',
        ),
    ]
